services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.14-bookworm
    volumes:
      # 현재 .devcontainer의 상위 폴더(stock)를 컨테이너 내부로 연결
      - ..:/workspaces/stock:cached
    working_dir: /workspaces/stock
    # 컨테이너 유지를 위한 명령
    command: sleep infinity
